### ISSUE TITLE
Invalid date string

### ISSUE THREAD

**Issue by pkq** [tidyverse/haven#230]
I'm getting an `Invalid date string` error when attempting to read in an SPSS file:

`Invalid date string (length=9): 11 FEB 1412:35:06`
`Error in eval(substitute(expr), envir, enclos) : `
`  Failed to parse file_name.sav: The file's timestamp string is invalid.`

I'm guessing it has to do with the fact that there's no space between the year and timestamp, but don't have any idea what would cause it, or how to fix it, and unfortunately, I'm not able to share the file. Any guidance is appreciated. Thanks!

**Comment by evanmiller** [comment]
Hi, do you know what program / version produced the SPSS file?

**Comment by pkq** [comment]
It was produced using SPSS, but I'm not sure which version it was. The file is a couple years old, so I'm guessing SPSS 20 or 21. The thing is, I'm almost positive I was able to read in this same file using an earlier version of haven. Has haven gotten more strict about requiring a valid timestamp? If so, is there any way to override this restriction?

**Comment by evanmiller** [comment]
Yes the underlying library (ReadStat) has become more strict with regard to timestamps. It actually looks like the issue is with the case of the month (ReadStat was expecting "Feb", not "FEB"). I will get this fixed soon.

**Comment by evanmiller** [comment]
Ok, this is fixed in ReadStat here: https://github.com/WizardMac/ReadStat/commit/688e5657cf8e0806c4464445a0d06c32a5d0e07d

**Comment by pkq** [comment]
Awesome, thanks for the prompt resolution! Does this require an update to haven before I can use this in R?

**Comment by evanmiller** [comment]
I think there's an update_readstat script or command so you don't have to wait -- this used to be documented in the README, but I don't see it now.

**Comment by tklebel** [comment]
Hadley moved it to a function: https://github.com/tidyverse/haven/commit/beab2274a9798a15a93dc2cc65a702327f697c2e

You should be able to call it like this: ```haven:::update_readstat()```.

**Comment by pkq** [comment]
It looks like `haven:::update_readstat()` worked, but I'm still getting the same `The file's timestamp string is invalid` error. Is there a way to confirm that I actually have the latest version of readstat?

**Comment by evanmiller** [comment]
Can you send me the SAV file that's failing? I can check it on my end. Verifying the ReadStat version can be a little complicated since in the past haven has sometimes omitted some of the source files.

**Comment by pkq** [comment]
Not sure what I was doing wrong, but updating to the Github version oh haven worked. Thanks @evanmiller!
